channels:
- conda-forge
dependencies:
- python=3.10.8
- pip<=22.2.2
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.0.0
  - numpy==1.26.2
  - packaging==23.2
  - pandas==2.1.4
  - psutil==5.9.7
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.4
  - xgboost==2.0.3
name: mlflow-env
